"""

    Pattern :

    An element in the output array is generated by multiplying all the elements in the input array,
    excluding the one present in the index corresponding to the output element.

    Example:

    Input : array = [5, 1, 4, 2]
    the first element of the output array is generated by multiplying the second, third and the fourth element,
    Output[0]= 1*4*2.
    similarly, the second element is generated by multiplying the first, third, and the fourth element,
    Output[1]= 5*4*2
    Output: array = [8,40,10,20]

    """

run = True
while run is True:

    # Taking user input

    input_list = []
    n = int(input("Enter the number of elements in list : "))
    for i in range(n):
        element = int(input(f"Enter the value of element {i + 1} : "))
        input_list.append(element)

    # Generating the output list

    output_list = []

    for i in range(n):
        element = 1
        for j in range(n):
            if j != i:  # Excluding the element at location corresponding to the element being generated.
                element = element * input_list[j]
        output_list.append(element)

    # Printing results

    print("Input : ", input_list)
    print("Output : ", output_list)

    run = input("Would you like to run the program again? (y/n) : ")
    if run != "Y" or "y":
        run = False
